export const GET_HISTORY_START='GET_HISTORY_START';
export const GET_HISTORY_SUCCESS='GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL='GET_HISTORY_FAIL';

export const GET_PAYLOAD_START='GET_PAYLOAD_START';
export const GET_PAYLOAD_SUCCESS='GET_PAYLOAD_SUCCESS';
export const GET_PAYLOAD_FAIL='GET_PAYLOAD_FAIL';